In [2]:
#GradienBoostModel
print('\n\n---------- from now, outputs are for GradientBoost -------------')

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(data, target, 
                                                                     test_size = 0.2, random_state = 42)


from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_validate
gb = GradientBoostingClassifier(random_state = 42)
scores = cross_validate(gb, train_input, train_target,
                       return_train_score = True, n_jobs = -1)
print(np.mean(scores['train_score'],), np.mean(scores['test_score']))

gb = GradientBoostingClassifier(n_estimators = 500, learning_rate = 0.2,
                               random_state = 42)
scores = cross_validate(gb, train_input, train_target,
                       return_train_score = True, n_jobs = -1)
print(np.mean(scores['train_score'],), np.mean(scores['test_score']))

gb.fit(train_input, train_target)
print('GradientBoosting model feature importances : ', gb.feature_importances_)



---------- from now, outputs are for GradientBoost -------------
0.8881086892152563 0.8720430147331015
0.9464595437171814 0.8780082549788999
GradientBoosting model feature importances :  [0.15881044 0.67988912 0.16130044]


In [20]:
#Histogram-Based Gradient Boosting Model
print('\n\n---------- from now, outputs are for Histogram_based Gradient Boosting -------------')
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state = 42)
scores = cross_validate(hgb, train_input, train_target,
                       return_train_score = True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

from sklearn.inspection import permutation_importance


hgb.fit(train_input, train_target)
#Compute feature importances on train_set
result = permutation_importance(hgb, train_input, train_target,
                               n_repeats = 3, random_state = 42, n_jobs=-1)
#np.array()를 이용해서 넘파이 배열로 바꿔서 출력하면 행렬이 구분되어서 출력되서 알아보기 쉽게 출력된다.
importances = np.array(result.importances)
print('importance : \n', importances)
print('importance mean : ', result.importances_mean, '\n')
print('alcohol importance ratio : ', result.importances_mean[0] / result.importances_mean.sum())
print('sugar importance ratio : ', result.importances_mean[1] / result.importances_mean.sum())
print('pH importance ratio : ', result.importances_mean[2] / result.importances_mean.sum())
print('\nimportace std : ', result.importances_std)



#Compoute feature importances on test_set
result = permutation_importance(hgb, test_input, test_target,
                               n_repeats=10, random_state = 42, n_jobs = -1)
print('\n\ntest_set_mean_of_importances : ', result.importances_mean)

print('Final score : ', hgb.score(test_input, test_target))



---------- from now, outputs are for Histogram_based Gradient Boosting -------------
0.9321723946453317 0.8801241948619236
importance : 
 [[0.08793535 0.08350972 0.08908986]
 [0.22782374 0.23590533 0.23936887]
 [0.08581874 0.08601116 0.08062344]]
importance mean :  [0.08684497 0.23436598 0.08415111] 

alcohol importance ratio :  0.21424050632911396
sugar importance ratio :  0.5781645569620253
pH importance ratio :  0.2075949367088608

importace std :  [0.00240502 0.00483733 0.00249568]


test_set_mean_of_importances :  [0.05969231 0.20238462 0.049     ]
Final score :  0.8723076923076923


In [34]:
#XGBoost - Histogram-Based Gradient Boosting Model
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method = 'hist', random_state = 42)
scores = cross_validate(xgb, train_input, train_target,
                       return_train_score = True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9558403027491312 0.8782000074035686


In [40]:
#LightGBM
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state = 42)
scores = cross_validate(lgb, train_input, train_target,
                        return_train_score = True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.935828414851749 0.8801251203079884
